FROM python:2.7

# python 2.7 is based on debian stretch, which is unsupported.
# packages are not available anymore, so we need to use the archive repositories

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list \
 && echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list \
 && echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/99no-check-valid-until \
 && apt-get update \
 && apt-get install -y --no-install-recommends wget unzip \
 && rm -rf /var/lib/apt/lists/*

# Requisites 
RUN pip install --no-cache-dir \
    "numpy<1.17" \
    "scipy<1.3" \
    "matplotlib<3" \
    "pandas<0.25" \
    "scikit-learn<0.21" \
    "statsmodels<0.11" \
    "reportlab<3.6"

# Downloads and install PhageTerm
WORKDIR /opt
RUN wget -O phageterm.zip "https://sourceforge.net/projects/phageterm/files/latest/download" \
 && unzip phageterm.zip -d phageterm \
 && rm phageterm.zip

ENV PATH="/opt/phageterm/phageterm-1.0.12/:${PATH}"

WORKDIR /workdir
